// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEF4EdPcsHyPj-XoN7BBJTDxqoggYfEnk',
    appId: '1:573911339006:ios:4620aad64f4b7bcff3baaf',
    messagingSenderId: '573911339006',
    projectId: 'cleanova-13d44',
    storageBucket: 'cleanova-13d44.firebasestorage.app',
    iosBundleId: 'com.example.cleanova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEF4EdPcsHyPj-XoN7BBJTDxqoggYfEnk',
    appId: '1:573911339006:ios:4620aad64f4b7bcff3baaf',
    messagingSenderId: '573911339006',
    projectId: 'cleanova-13d44',
    storageBucket: 'cleanova-13d44.firebasestorage.app',
    iosBundleId: 'com.example.cleanova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ojzvBz0ODbZVq-PSkILHF7unYh2zJJ0',
    appId: '1:573911339006:web:0eba3e909175a838f3baaf',
    messagingSenderId: '573911339006',
    projectId: 'cleanova-13d44',
    authDomain: 'cleanova-13d44.firebaseapp.com',
    storageBucket: 'cleanova-13d44.firebasestorage.app',
    measurementId: 'G-BKCD9V2RZK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ojzvBz0ODbZVq-PSkILHF7unYh2zJJ0',
    appId: '1:573911339006:web:0eba3e909175a838f3baaf',
    messagingSenderId: '573911339006',
    projectId: 'cleanova-13d44',
    authDomain: 'cleanova-13d44.firebaseapp.com',
    storageBucket: 'cleanova-13d44.firebasestorage.app',
    measurementId: 'G-BKCD9V2RZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3X2I9xMsyRWSgOGfuYwELHeBzWUQj6Ag',
    appId: '1:573911339006:android:44ac92ad0b74aeeff3baaf',
    messagingSenderId: '573911339006',
    projectId: 'cleanova-13d44',
    storageBucket: 'cleanova-13d44.firebasestorage.app',
  );

}